export const aboutLines = [
    "class Introduction:",
    "    def __init__(self):",
    '        self.name = "Samuel Emard-Thibault"',
    '        self.email = "sam5thibault@gmail.com"',
    '        self.role = "Incoming Production Engineer @ Meta"',
    '        self.education = "BASc Computer Engineering, Queen\'s University (ON, Canada)"\n\n',
    '     def print_intro(self):',
    '        print("Hi there, welcome to my portfolio! The clickable links for the socials are above, thanks for stopping by :)")\n\n',
    "     def core_skills(self):",
    "        return {",
    '            "Languages": ["Python", "JS/TS", "C/C++", "Java", "Bash"],',
    '            "Frameworks": ["Django REST", "Flask", "React/Next", "Flutter", "Express"],',
    '            "Tools": ["Linux", "Git", "AWS", "Docker", "SQL/NoSQL", "GCP", "OCI"]',
    "        }",
  ];
  
export const experienceLines = [
    "|----------------|---------------------|--------------------|",
    "|    Date        |       Company       |         Role       |",
    "|----------------|---------------------|--------------------|",
    "| 2024-2025      | Smith School of     | Research Assistant |",
    "|                | Business, Queen's   |                    |",
    "|----------------|---------------------|--------------------|",
    "| 2023-2024      | Centre for Advanced | Software Developer |",
    "|                | Computing           | Intern             |",
    "|----------------|---------------------|--------------------|",
    "| 2022-2025      | Self-employed       | ",
    "|----------------|---------------------|--------------------|",
  ];