version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always
