name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run:  |
          mkdir -p /home/runner/.ssh/
          echo "$SSH_PRIVATE_KEY" > /home/runner/.ssh/deploy-key.pem
          chmod 600 /home/runner/.ssh/deploy-key.pem
          cat >> /home/runner/.ssh/config <<END
          Host my-vps
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile /home/runner/.ssh/deploy-key.pem
            StrictHostKeyChecking no
            port $SSH_PORT
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Deploy site
        run: ssh my-vps 
          'chmod +x ${{ secrets.PROJECT_ROOT }}/shell_scripts/redeploy-site.sh &&
          ${{ secrets.PROJECT_ROOT }}/shell_scripts/redeploy-site.sh &&
          cd ${{ secrets.PROJECT_ROOT }}'

  notify:
    needs: deploy
    name: "Notify on Discord"
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Success Notification
        if: ${{ needs.deploy.result == 'success' }}
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚀 Deployment Successful"
      - name: Error Notification
        if: ${{ needs.deploy.result == 'failure' }}
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=Deployment Error :("